name: Alpine

on: push

jobs:
  alpine:
    runs-on: ubuntu-22.04
    container: alpine:latest
    steps:
      - name: Install and prepare Git
        run: |
          apk update && apk upgrade
          apk add git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          apk update
          apk add cmake g++ make pkgconf
      - name: Build
        run: |
          cd "$GITHUB_WORKSPACE"
          mkdir build
          cd build
          export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
          cmake ../
          cmake --build . -j2
      - name: Build statically linked executable
        run: |
          cd "$GITHUB_WORKSPACE"
          mkdir build-static
          cd build-static
          export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
          cmake ../ -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON
          cmake --build . -j2
      - name: Collect build artifacts
        run: |
          mkdir -p "$GITHUB_WORKSPACE"/artifacts
          cd "$GITHUB_WORKSPACE"
          # binary file
          cp build-static/src/compare-ini artifacts/
          # license + changelog + readme + third-party notices
          cp LICENSE artifacts/
          cp CHANGELOG.md artifacts/
          cp README.md artifacts/
          cp documentation/third-party.md artifacts/
          # determine version
          VERSION=$(git describe --always)
          echo Version is $VERSION.
          mv artifacts compare-ini-$VERSION
          tar czf compare-ini_${VERSION}_linux-amd64-generic.tar.gz compare-ini-$VERSION
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compare-ini_linux-amd64-generic
          path: compare-ini_*_linux-amd64-generic.tar.gz
          if-no-files-found: error
