name: Clang

on: push

jobs:
  clang:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version: [14, 16, 18]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch2 cmake clang-${{ matrix.version }} pkg-config
      - name: Build with Clang ${{ matrix.version }}
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j2
      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Statically linked build with Clang ${{ matrix.version }}
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build-static
          cd build-static
          cmake ../ -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON
          make -j2
      - name: Run tests for statically linked version
        run: |
          cd "$GITHUB_WORKSPACE"/build-static
          ctest -V
