name: GCC

on: push

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 10
            os: ubuntu-22.04
          - version: 11
            os: ubuntu-22.04
          - version: 12
            os: ubuntu-22.04
          - version: 13
            os: ubuntu-24.04
          - version: 14
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch2 cmake g++-${{ matrix.version }} pkg-config
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j2
      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Statically linked build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build-static
          cd build-static
          cmake ../ -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON
          make -j2
      - name: Run tests for statically linked version
        run: |
          cd "$GITHUB_WORKSPACE"/build-static
          ctest -V
